name: setask
description: A new Flutter project.



publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  google_sign_in: ^5.0.7
  meta: ^1.3.0
  very_good_analysis: ^2.4.0
  formz: ^0.4.1
  font_awesome_flutter: ^10.1.0
  flow_builder: ^0.0.6
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  flutter_localizations:
      sdk: flutter
  shared_preferences: ^2.0.13
  task_repository:
    path: packages/task_repository
  firebase_task_data_api:
    path: packages/firebase_task_data_api

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^1.0.0



flutter:
  uses-material-design: true
  generate: true
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
