name: firebase_repository
description: firebase repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  meta: ^1.3.0
  very_good_analysis: ^2.4.0
  cloud_firestore: ^3.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0