// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUs4JReFxsaGFRtG47SUEqyRIGA7qQUSk',
    appId: '1:621049794869:web:9635c2fccc64a93c5ffc7c',
    messagingSenderId: '621049794869',
    projectId: 'setask-b1a1b',
    authDomain: 'setask-b1a1b.firebaseapp.com',
    storageBucket: 'setask-b1a1b.appspot.com',
    measurementId: 'G-PKT44LK7DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDasCWv-5tUYUaq5YkRuFLCYEtU4thiYwU',
    appId: '1:621049794869:android:665231fb269e23a65ffc7c',
    messagingSenderId: '621049794869',
    projectId: 'setask-b1a1b',
    storageBucket: 'setask-b1a1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUZRyaUSMEnsxmpN-NCrkUXEsQbHwDEg',
    appId: '1:621049794869:ios:9f63302bed026bf45ffc7c',
    messagingSenderId: '621049794869',
    projectId: 'setask-b1a1b',
    storageBucket: 'setask-b1a1b.appspot.com',
    iosClientId: '621049794869-6c8i4ehq65m0mt01finml69q0p2gv7vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.setask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUZRyaUSMEnsxmpN-NCrkUXEsQbHwDEg',
    appId: '1:621049794869:ios:9f63302bed026bf45ffc7c',
    messagingSenderId: '621049794869',
    projectId: 'setask-b1a1b',
    storageBucket: 'setask-b1a1b.appspot.com',
    iosClientId: '621049794869-6c8i4ehq65m0mt01finml69q0p2gv7vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.setask',
  );
}
