name: firebase_task_data_api
description: firebase_task_data_api
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.12
  firebase_core: ^1.5.0
  firebase: ^9.0.2
 



dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
